[package]
name = "shdwview"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.20.0"
clap = { version = "4.5.21", features = ["derive"] }
eframe = "0.29.1"
egui = { version = "0.29.1", features = ["bytemuck"] }
egui_plot = "0.29.0"
image = "0.25.5"
itertools = "0.13.0"
