[package]
name = "shadowcast"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.20.0", features = ["derive"] }
clap = { version = "4.5.21", features = ["derive"] }
contour_tracing = { version = "1.0.12", features = ["array"] }
image = "0.25.5"
svg = "0.18.0"
